#pragma once

typedef enum {
	S3K_SUCCESS = 0,
	S3K_ERR_EMPTY,
	S3K_ERR_SRC_EMPTY,
	S3K_ERR_DST_OCCUPIED,
	S3K_ERR_INVALID_INDEX,
	S3K_ERR_INVALID_DERIVATION,
	S3K_ERR_INVALID_MONITOR,
	S3K_ERR_INVALID_PID,
	S3K_ERR_INVALID_STATE,
	S3K_ERR_INVALID_PMP,
	S3K_ERR_INVALID_SLOT,
	S3K_ERR_INVALID_SOCKET,
	S3K_ERR_INVALID_SYSCALL,
	S3K_ERR_NO_RECEIVER,
	S3K_ERR_PREEMPTED,
	S3K_ERR_TIMEOUT,
	S3K_ERR_SUSPENDED,
} s3k_err_t;
