[constants]
prefix = 'riscv64-unknown-elf-'
arch   = 'rv64imac_zicsr'
abi    = 'lp64'
cmodel = 'medany'

[binaries]
c       = prefix + 'gcc'
cpp     = prefix + 'cpp'
ld      = prefix + 'ld'
ar      = prefix + 'ar'
as      = prefix + 'as'
size    = prefix + 'size'
objdump = prefix + 'objdump'
objcopy = prefix + 'objcopy'
strip   = prefix + 'strip'

[built-in options]
c_args = [
	'-march=' + arch, 
	'-mabi=' + abi, 
	'-mcmodel=' + cmodel 
	]
c_link_args = [
	'-march=' + arch, 
	'-mabi=' + abi, 
	'-mcmodel=' + cmodel
	]

[host_machine]
system     = 'baremetal'
cpu_family = 'riscv64'
cpu        = 'riscv64'
endian     = 'little'
