#pragma once

typedef enum {
	SUCCESS = 0,
	ERR_EMPTY,
	ERR_SRC_EMPTY,
	ERR_DST_OCCUPIED,
	ERR_INVALID_CLIENT,
	ERR_INVALID_DERIVATION,
	ERR_INVALID_INDEX,
	ERR_INVALID_MONITOR,
	ERR_INVALID_PID,
	ERR_INVALID_PMP,
	ERR_INVALID_SERVER,
	ERR_INVALID_SLOT,
	ERR_INVALID_STATE,
	ERR_INVALID_SYSCALL,
	ERR_NO_RECEIVER,
	ERR_PREEMPTED,
	ERR_TIMEOUT,
	ERR_SUSPENDED,
	// Special values.
	JUSTRET,
	SYNC,
	IPC_SYNC,
	YIELD,
} err_t;
